parameters:
#    labo_contenu.example.class: Labo\ContenuBundle\Example

services:
#    labo_contenu.example:
#        class: %labo_contenu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
